### ISSUE TITLE
Is it possible to make vscode-cpptools a separate plugin just like nvim-dap-python?

### ISSUE THREAD

**Issue by cogig** [mfussenegger/nvim-dap#202] opened 2021-06-09 12:30 UTC
The installation steps of vscode-cpptools are tedious. After the installation is completed, the configuration in the cookbook does not work properly. Maybe lldb-vscode is an alternative option, but more users choose gdb over lldb for debugging on linux.

**Comment by mfussenegger** [comment] 2021-06-09 16:11
Maybe something to bring up in https://github.com/Pocco81/DAPInstall.nvim

I use lldb-vscode myself and rarely use c/c++/rust, so you won't be seeing anything in that direction from my side but everybody is welcome to step up und create a separate plugin

**Comment by cogig** [comment] 2021-06-10 00:58
According to the cookbook, my configuration is as follows.
```
M.start_c_debugger = function(args, mi_mode, mi_debugger_path)
    local dap = require "dap"
    if args and #args > 0 then
        last_gdb_config = {
            type = "cpp",
            name = args[1],
            request = "launch",
            program = table.remove(args, 1),
            args = args,
            cwd = vim.fn.getcwd(),
            externalConsole = false,
            MIMode = "gdb",
            MIDebuggerPath = "/usr/bin/gdb"
          }
    end

    if not last_gdb_config then
        print('No binary to debug set! Use ":DebugC <binary> <args>" or ":DebugRust <binary> <args>"')
        return
    end

    dap.run(last_gdb_config)
end

dap.adapters.cpp = {
    type = 'executable',
    name = "cppdbg",
    command = os.getenv('HOME') .. '/.ndap_debugger/ms-vscode.cpptools-1.4.1/debugAdapters/OpenDebugAD7',
    args = {},
    attach = {
        pidProperty = "processId",
        pidSelect = "ask"
    }
}
```
This is the work state of nvim-dap.

![image](https://user-images.githubusercontent.com/45864384/121448273-e30fb900-c9c9-11eb-8869-821289157808.png)

**Comment by mfussenegger** [comment] 2021-06-10 10:32
@cogig I assume the problem is that the breakpoint isn't hit? Did you compile your application with debug symbols?

Otherwise logs would be helpful (see `:help dap.set_log_level()`)

**Comment by mfussenegger** [comment] 2021-06-11 12:10
Looks like your issue might be caused by nvim-dap-ui see https://github.com/Pocco81/DAPInstall.nvim/issues/4#issuecomment-859498075 and https://github.com/rcarriga/nvim-dap-ui/issues/22

I'm closing this here because as far as I  can tell there is nothing actionable to do within nvim-dap itself

**Closed** 2021-06-11 12:10 UTC

**Comment by nyngwang** [comment] 2023-08-05 05:32
@cogig What's the name of the colorscheme you used?
