### ISSUE TITLE
Unable to attach to process using netcoredbg

### ISSUE THREAD

**Issue by rudiejd** [mfussenegger/nvim-dap#1142] opened 2024-01-18 14:32 UTC
### Debug adapter definition and debug configuration

```lua      
dap.adapters.netcoredbg = {
  type = 'executable',
  command = 'netcoredbg',
  args = { '--interpreter=vscode' },
}

dap.configurations.cs = {
  {
    type = 'netcoredbg',
    name = 'Attach - netcoredbg',
    request = 'attach',
    processId = require('dap.utils').pick_process
  },
}
```

### Debug adapter version

3.0.0-1012 

### Steps to Reproduce

1. Use the attach configuration
2. Pick any process
3. Observe the error

### Expected Result

Should attach to process and begin debugging

### Actual Result

`Error on attach: can't parse: [json.exception.out_of_range.403] key 'processId' not found`

**Comment by mfussenegger** [comment] 2024-02-04 10:29
Closing as duplicate of https://github.com/mfussenegger/nvim-dap/issues/356 - and not a client issue.

**Closed by mfussenegger** 2024-02-04 10:29 UTC
