### ISSUE TITLE
Sign priority lower than LSP error diagnostics when `severity_sort = true` is set.

### ISSUE THREAD

**Issue by kiyoon** [mfussenegger/nvim-dap#920] opened 2023-04-05 14:09 UTC
### Steps to Reproduce

```lua
  local config = {
    -- virtual_text = true,
    virtual_text = { spacing = 3, prefix = "" },
    signs = {
      active = signs, -- show signs
    },
    update_in_insert = true,
    underline = true,
    -- This will cover the DAP breakpoints
    severity_sort = true,
    float = {
      focusable = true,
      style = "minimal",
      border = "rounded",
      source = "always",
      header = "",
      prefix = "",
    },
  }

  vim.diagnostic.config(config)
```

The `severity_sort = true` was causing the trouble.

### Expected Result

Sign priority should be LspWarning <  LspError < DapBreakpoint with `severity_sort = true` option in the LSP config.

### Actual Result

Sign priority seems to be LspWarning < DapBreakpoint < LspError if `severity_sort = true` option is given in the LSP config.

It looks like the priority value in `vim.fn.sign_place` is hardcoded to 11 in this plugin. I fixed it by turning that option off, but maybe it should be more flexible or detect the priority of the diagnostic sign automatically.

**Comment by mfussenegger** [comment] 2023-04-05 15:39
Duplicate of https://github.com/mfussenegger/nvim-dap/issues/197

**Closed by mfussenegger** 2023-04-05 15:39 UTC

**Comment by kiyoon** [comment] 2023-04-11 16:55
#197 suggests a way to configure priority from users, but the solution to this can be as simple as making the default priority higher than what it is now. Or I think there could be a way to get the priority of the diagnostic error and then make it higher than that.

`severity_sort` is also a core functionality, so providing a good default to match the core is something that should be considered in my opinion.
