### ISSUE TITLE
delve remote: Connection is closed

### ISSUE THREAD

**Issue by tttoad** [mfussenegger/nvim-dap#866] opened 2023-02-18 19:12 UTC
### Debug adapter definition and debug configuration

config:
```
{
		type = 'delve';
		name = 'remote-test';
		request = 'launch';
		mode = "debug";
		showLog = true;
		program = "${file}";
		outputMode = 'only-remote';
}
```

### Steps to Reproduce

1. Run delve. (cmd:  delve --dap -l 0.0.0.0:38697 --log --log-output=dap)
2. Run dap-client.

### Expected Result

Print: "Process xxx has exited with status xx\n"

### Actual Result

delve log:
```
2023-02-19T02:58:40+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2023-02-19T02:58:40+08:00 debug layer=dap DAP error: EOF
2023-02-19T02:58:40+08:00 debug layer=dap DAP server stopping...
2023-02-19T02:58:40+08:00 debug layer=dap halting
2023-02-19T02:58:40+08:00 debug layer=dap process not running
2023-02-19T02:58:40+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"console",
"output":"Process 6249 has exited with status 0\n","source":{}}}
2023-02-19T02:58:40+08:00 debug layer=dap write tcp 127.0.0.1:38697->127.0.0.1:52623: use of closed network connection
2023-02-19T02:58:40+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"output","body":{"category":"console",
"output":"Detaching\n","source":{}}}
2023-02-19T02:58:40+08:00 debug layer=dap write tcp 127.0.0.1:38697->127.0.0.1:52623: use of closed network connection
2023-02-19T02:58:40+08:00 debug layer=dap DAP server stopped
```
The delve will send  "terminated" event after sending "Process 6043 has exited with status 0\n".

**Comment by mfussenegger** [comment] 2023-02-19 06:16
On a first glance this looks like an issue with delve. `delve` sends a terminated event which indicates the end of the debugging session and nvim-dap closes the connection.

Changing that behavior would break the handling with other debug adapters. I could defer the closing a bit to give it time for other messages, but that doesn't really seem the right thing to do to me.

**Comment by tttoad** [comment] 2023-02-19 12:29
I would like to know, is there any documentation for this process?
I found this "https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated".
Maybe "delve" needs to use the "exited" event?

**Comment by mfussenegger** [comment] 2023-02-22 16:35
The problem is that they send the terminated event before the output events. If they sent them before it would work fine.

If I removed the session-closing from the terminated event, the session would remain open indefinitely with other debug adapters.

**Closed** 2023-11-01 14:01 UTC
