### ISSUE TITLE
Breakpoints stopped working after upgrading from GCC 10 to GCC 11

### ISSUE THREAD

**Issue by Shatur** [mfussenegger/nvim-dap#186] opened 2021-05-20 22:18 UTC
I used GGC 10.2 and it worked as expected. But after upgrading to GCC 11.1.0, the application no longer stop at breakpoints. Has anyone encountered such a problem?
I use `lldb-vscode` from LLVM 11.1.0.

**Comment by mfussenegger** [comment] 2021-06-01 19:15
I noticed the same but didn't investigate further yet. Seems like a regression in lldb-vscode?

**Comment by Shatur** [comment] 2021-06-01 19:17
Perhaps lldb-vscode simply does not support `dwarf-5`, which is the default in GCC 11. I just temporarily switched to `dwarf-4` and it works.

**Comment by rmagillxyz** [comment] 2021-06-08 15:57
Not sure if this is related, but I was having issues with the breakpoints being set, but then skipped. I found if I delete the line and then add it back with a breakpoint, then it works as expected.

**Comment by mfussenegger** [comment] 2021-07-14 20:06
> Not sure if this is related, but I was having issues with the breakpoints in go being set, but then skipped. I found if I delete the line and then add it back with a breakpoint, then it works as expected.

This sounds like a separate issue.  Could you create a new one with reproduction steps? 

Going to close this one since it was/is a debug adapter issue,  not a client issue

**Closed by mfussenegger** 2021-07-14 20:06 UTC
