### ISSUE TITLE
Debug adpater reported a frame at line 74, cursor position outside buffer.

### ISSUE THREAD

**Issue by akashdiphazra** [mfussenegger/nvim-dap#956] opened 2023-05-21 17:33 UTC
### Debug adapter definition and debug configuration

C/C++ Debugger Doesn't exit properly.
```lua
local dap = require('dap')
dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = '/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7',
}
dap.configurations.cpp = {
  {
    name = "vscode-cpptools",
    type = "cppdbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    launchCompleteCommand = "exec-run",
    stopAtEntry = false,
    miDebuggerArgs = "-x ./.gdbinit",
    setupCommands = {
      {
        text = '-enable-pretty-printing',
        description = 'enable pretty printing',
        ignoreFailures = false
      },
    },
  },
  {
    name = 'gdbserver',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    cwd = '${workspaceFolder}',
    miDebuggerPath = '/usr/bin/gdb',
    miDebuggerArgs = "-x ./.gdbinit",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}


```

### Debug adapter version

0.6.0

### Expected Result

Debugger should stop and exit.

### Actual Result

[Screencast from 2023-05-21 22-23-51_trimmed.webm](https://github.com/mfussenegger/nvim-dap/assets/61003681/d6265ab2-0a31-42fe-a2aa-de6cbf888a64)

**Comment by mfussenegger** [comment] 2023-05-23 16:37
Part of the idea behind reproduction steps is that one can follow them to reproduce the problem.

**Comment by akashdiphazra** [comment] 2023-05-24 13:32
### I tried to skip stl and other .h files , so that it's doesn't step into unnecessary implementation, It's disturbing and overwhelming during debugging process because unnecessary files open randomly. Unlike vscode and visual studio debugger JusMyCode feature never works or not fully implement yet even on windows also , it tried many times but failed. So the last option was using .gdbinit file.
my .gdbinit file

````shell
skip -gfi /usr/include/c++/12/*/*/*
skip -gfi /usr/include/c++/12/*/*
skip -gfi /usr/include/c++/12/*
````
Dap log file

````text
[ ERROR ] 2023-05-24T18:19:38Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:20:05Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"


[ ERROR ] 2023-05-24T18:45:24Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:45:34Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"

[ ERROR ] 2023-05-24T18:52:20Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:52:21Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
````
#### After removing  miDebuggerArgs = "-x ./.gdbinit" same thing appears. Results of log file after removing that part. 

````text
[ ERROR ] 2023-05-24T18:19:38Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:20:05Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"


[ ERROR ] 2023-05-24T18:45:24Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:45:34Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"

[ ERROR ] 2023-05-24T18:52:20Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:52:21Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
[ INFO ] 2023-05-24T18:53:46Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/DebugCompleted"
[ INFO ] 2023-05-24T18:53:46Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1695 ]	"Session closed due to disconnect"

[ ERROR ] 2023-05-24T18:54:35Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:54:36Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
[ INFO ] 2023-05-24T18:55:18Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/DebugCompleted"
[ INFO ] 2023-05-24T18:55:18Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1695 ]	"Session closed due to disconnect"


[ ERROR ] 2023-05-24T18:55:55Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1342 ]	"stderr"	{
  command = "/usr/local/nvim-dap-adapters/cpp-tools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2023-05-24T18:55:56Z+0530 ] ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:729 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
````
my configuration remains same as provided above.

**Comment by nezos** [comment] 2023-06-04 22:26
Same issue with codelldb installed.

Any C++ simple file:

set breakpoint
run
keep executing next line until end
debugger enters dissasembly and the error appearing is the same as reported 2 weeks ago:
"Debug adapter reported a frame at line .... Cursor outside buffer..."

After the error the source file is closed and neovim plugins become unresponsive. Only solution is to quit.

My config and a sample cpp file:
[debug.txt](https://github.com/mfussenegger/nvim-dap/files/11647344/debug.txt)
[test.txt](https://github.com/mfussenegger/nvim-dap/files/11647346/test.txt)

**Comment by Aeceon** [comment] 2023-06-09 16:52
I think the issue might be here in [session.lua](https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/session.lua#LL417C1-L427C6):
```lua
 function switchbuf_fn.uselast()
    if vim.bo[cur_buf].buftype == '' or vim.bo[cur_buf].filetype == filetype then
      api.nvim_win_set_buf(cur_win, bufnr)
      set_cursor(cur_win, line, column)
    else
      local win = vim.fn.win_getid(vim.fn.winnr('#'))
      api.nvim_win_set_buf(win, bufnr)
      set_cursor(win, line, column)
    end
return true
```
I believe the disassembly buffer is type nofile and is therefore going to the else branch when it shouldn't. If you haven't switched windows it probably won't cause issues, but if you have, the "Cursor outside buffer" error will occur.

I haven't tested it, but it looks like there might be another issue here if you switch between multiple windows. The call to "vim.fn.winnr('#')" will get the last accessed window, but couldn't this potentially be the wrong window? Especially if you use [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui).

**Comment by mfussenegger** [comment] 2023-06-09 17:06
I'd still need _minimal_ and _complete_ reproduction steps. "Any c++" file is not sufficient.

**Comment by nezos** [comment] 2023-06-10 04:55
> I'd still need _minimal_ and _complete_ reproduction steps. "Any c++ file" is not sufficient.

A test file could be (test.cpp):

`#include <iostream>
#include <iomanip>
#include <ostream>

int main()
{
  float      testf{0.123456789012345678901234567890};
  double     testd{0.123456789012345678901234567890};
  long double test{0.123456789012345678901234567890};
  std::cout << std::fixed << std::setprecision(20) << test << std::endl;
  std::cout << std::fixed << std::setprecision(20) << testf << std::endl;
  std::cout << std::fixed << std::setprecision(20) << testd << std::endl;
  std::cout << std::numbers::pi << std::endl;

  return 0;
}
`
And the CMakeLists.txt

`cmake_minimum_required(VERSION 3.25)  # CMake version check
project(my_example)               # Create project "simple_example"
set(CMAKE_CXX_STANDARD 20)            # Enable c++20 standard

# Add main.cpp file of project root directory as source file
set(SOURCE_FILES test.cpp)

# Add executable target with source files listed in SOURCE_FILES variable
add_executable(test ${SOURCE_FILES})
`

My neovim configuration:
[nvim-configuration.zip](https://github.com/mfussenegger/nvim-dap/files/11711544/nvim-configuration.zip)



And steps to reproduce:
1) Run nvim test.cpp
2) :CMakeGenerate
3) :CMakeBuild
4) Set a breakpoint at any line, e.g., line 15. (space+B for my config)
5) Press F7 to switch to debug mode windows arrangement
6) Continue debug
7) Breakpoint hits. Step over until the end of program (return 0)
8) Step over again to next line and it goes to dissasembly
9) Press again to go to next line and error message appears + nvim becomes unresponsive -> need to close everything and start over to use it.

**Comment by mfussenegger** [comment] 2023-06-13 18:28
The zip file is empty (?) and this doesn't look _minimal_. Ideall it would be a simple file, some `g++` command, and plain neovim with _only_ nvim-dap required, to rule out that any other plugins are interferring somehow.

**Comment by akashdiphazra** [comment] 2023-06-14 04:59
You could go and check my repo, I have open-sourced my config, I  use lunarvim by the way ![Lvim](https://github.com/akashdiphazra/.dotfiles/tree/main/lvim)

**Comment by geo-ant** [comment] 2023-09-20 04:59
I have the same problem (also using the cmake tools plugin as the poster above). I'd be willing to try to produce a minimal config, but I don't know how to use nvim-dap without the help of cmake tools. Can someone point me to somewhere I can see how to do that?

**Comment by bret-walda** [comment] 2023-10-03 15:32
I am getting the same error while doing this with rust 
This is my dap configuration 
`local dap = require('dap')
dap.adapters.codelldb = {
    type = 'server',
    port = "${port}",
    executable = {
        command = '/home/bret/Downloads/extension/adapter/codelldb',
        args = {"--port", "${port}"},
    },
}
dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "codelldb",
    request = "launch",
    program = function()
        return vim.fn.input('Path to executable: ', vim.fn.getcwd()..'/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
  },
}
dap.configurations.rust = dap.configurations.cpp`

This is how you can reproduce the error 

1. cargo new "your project name"
2. cd "your project name" 
3. cd src
4. nvim main.rs
5. the main file consists of this code 
`fn patter(a: &mut i64) -> i64 {
-> B for _i in 1..10{
 *a +=1;
-> B println!("The value of a is {}",a);
}
return *a;
}

fn main(){
let mut x: i64 = 0;
pattern(&mut x);
}

`
then add break points and debug the code step into first time the code breaks into assembly and i get the same error

**Comment by mfussenegger** [comment] 2023-10-03 19:27
Your example works fine for me and doesn't produce any errors.

**Comment by bret-walda** [comment] 2023-10-03 20:23
> Your example works fine for me and doesn't produce any errors.

Would you be kind enough to check my dot files they are on my GitHub maybe I haven't configured nvim-dap correctly otherwise I will try again and post the screen recording of what happens in the morning I can't right now because of load shedding.

**Comment by bret-walda** [comment] 2023-10-04 06:50
> Your example works fine for me and doesn't produce any errors.


https://github.com/mfussenegger/nvim-dap/assets/43516908/ef22e231-988e-4bd9-8019-ad9f4a93143b

**Comment by bret-walda** [comment] 2023-10-04 07:42
> Your example works fine for me and doesn't produce any errors.

[cut.webm](https://github.com/mfussenegger/nvim-dap/assets/43516908/f1d1cc23-6ebd-441c-a487-3accd0e3911a)

This is what i get i have just realized this that if i keep pressing F1 which is the key to step into the program techinically keeps debugging but you can see in the vid that the code turns into assembly but keeps running until it is done.

**Comment by Aeceon** [comment] 2023-10-05 10:30
@bret-walda, if you try it without [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui), does the error still occur?

**Comment by bret-walda** [comment] 2023-10-05 11:50
> @bret-walda, if you try it without [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui), does the error still occur?

I haven't tried I will let you know in some time.

**Comment by bret-walda** [comment] 2023-10-05 16:58
> @bret-walda, if you try it without [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui), does the error still occur?

i just tried it without nvim-dap-ui i just didn't press the key to start it and added the break points stepped into it and it still happened. I don't know if i should uninstall nvim-dap-ui and try again but it did the same thing without nvim-dap-ui.

**Comment by mfussenegger** [comment] 2023-10-07 07:49
Please try with a minimal config:

E.g.:

`minimal.lua`:

```lua
local dap = require("dap")
dap.adapters.codelldb = {
  type = 'server',
  port = "${port}",
  executable = {
    command = os.getenv("HOME") .. "/apps/codelldb/extension/adapter/codelldb",
    args = {"--port", "${port}"},
  }
}
dap.configurations.rust = {
  {
    name = "codelldb: Launch",
    type = "codelldb",
    request = "launch",
    program = function()
      return vim.fn.input({
        prompt = "Path to executable: ",
        default = vim.fn.getcwd() .. "/",
        completion = "file"
      })
    end,
    cwd = '${workspaceFolder}',
    args = {},
  },
}
```

And then start `nvim` with `nvim -u ~/path/to/minimal.lua`

**Comment by bret-walda** [comment] 2023-10-10 09:27
> Please try with a minimal config:
> 
> E.g.:
> 
> `minimal.lua`:
> 
> ```lua
> local dap = require("dap")
> dap.adapters.codelldb = {
>   type = 'server',
>   port = "${port}",
>   executable = {
>     command = os.getenv("HOME") .. "/apps/codelldb/extension/adapter/codelldb",
>     args = {"--port", "${port}"},
>   }
> }
> dap.configurations.rust = {
>   {
>     name = "codelldb: Launch",
>     type = "codelldb",
>     request = "launch",
>     program = function()
>       return vim.fn.input({
>         prompt = "Path to executable: ",
>         default = vim.fn.getcwd() .. "/",
>         completion = "file"
>       })
>     end,
>     cwd = '${workspaceFolder}',
>     args = {},
>   },
> }
> ```
> 
> And then start `nvim` with `nvim -u ~/path/to/minimal.lua`

Doesn't change anything but if i stepover instead of stepping in the code doesn't turn into assembly and the debugger runs fine until the control flow goes out of the breakpoints and into the main function and at that point the process exits with code 0.

**Comment by Enigama** [comment] 2023-10-28 09:13
I have the same warning message each time I press step into, any suggestions how to solve it?
![image](https://github.com/mfussenegger/nvim-dap/assets/28072229/78187121-3311-43c2-a858-f7c96002122e)

**Comment by bret-walda** [comment] 2023-10-28 14:40
> I have the same warning message each time I press step into, any suggestions how to solve it? ![image](https://user-images.githubusercontent.com/28072229/278803142-78187121-3311-43c2-a858-f7c96002122e.png)

Try to stepover and see if that works else do what mfussenegger suggested but there is no clear solution yet

**Comment by Enigama** [comment] 2023-10-29 17:08
> > I have the same warning message each time I press step into, any suggestions how to solve it? ![image](https://user-images.githubusercontent.com/28072229/278803142-78187121-3311-43c2-a858-f7c96002122e.png)
> 
> 
> 
> Try to stepover and see if that works else do what mfussenegger suggested but there is no clear solution yet

What he had suggested?

**Comment by Parsifa1** [comment] 2023-11-05 18:35
I found that if I turn off stopAtEntry, the whole dap can work normally, otherwise the cursor position outside buffer will appear
![image](https://github.com/mfussenegger/nvim-dap/assets/31800073/4226e8b2-b033-498d-88ac-1c59b4ce9db1)

**Comment by BitInByte** [comment] 2023-11-23 12:11
I'm running into the same problem with firefox adapter. Only with step into, stepover works fine.

**Comment by bogdan-nikitin** [comment] 2023-12-29 17:22
I have the same problem with C++ and lldb-vscode. Minimal `init.lua`:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
{
    "mfussenegger/nvim-dap",
    config = function() 
        local dap = require('dap')
        dap.adapters.lldb = {
            type = 'executable',
            command = '/sbin/lldb-vscode',  --Change to your path
            name = 'lldb',
        }

        dap.configurations.cpp = {
          {
            name = "Launch file",
            type = "lldb",
            request = "launch",
            program = function()
              return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
            end,
            cwd = '${workspaceFolder}',
            stopOnEntry = false,
          },
        }

        vim.keymap.set('n', '<F5>', require 'dap'.continue)
        vim.keymap.set('n', '<F9>', require 'dap'.step_into)
    end
}
})
```

Steps to reproduce almost the same problem:
1. `nvim main.cpp`
2. Paste next code:
```c++
int main() {
  // breakpoint here
}
```
3. Compile running `:!clang -g % -o out`
4. Put breakpoint on 2nd line (SPC + b)
5. Create new window with `:new`
6. Switch back to previous window (CTRL-w + CTRL-p)
7. Run debugger (F5) and specify path to the `out` file
8. Step into few times (F9)

Assembly will appear in both windows

**Comment by mfussenegger** [comment] 2024-06-01 10:34
Closing this given that I haven't been able to reproduce the issue with any of the examples given.

**Closed by mfussenegger** 2024-06-01 10:34 UTC
Labels: needs: reproduction
