### ISSUE TITLE
Bad argument #3 to 'getaddrinfo' (Invalid protocol hint)

### ISSUE THREAD

**Issue by Matsuuu** [mfussenegger/nvim-dap#402] opened 2022-01-10 08:43 UTC
### Debug adapter definition and debug configuration

Heya, I'm trying to get nvim-dap working with nvim-jdtls.

My current setup is the following:

In JDTLS configuration:

```lua
    on_attach = function(client, bufnr)
      local jdtls = require('jdtls')
      jdtls.setup_dap({ hotcodereplace = 'auto' })
      jdtls.setup.add_commands()
    end

```

In dap configuration:

```lua
  local dap = require('dap')
  dap.adapters.java = function(callback)
    -- here a function needs to trigger the `vscode.java.startDebugSession` LSP command
    -- The response to the command must be the `port` used below
    callback({
      type = 'server';
      host = '127.0.0.1';
      port = 5005;
    })
  end

  dap.configurations.java = {
    {
      type = 'java';
      request = 'attach';
      name = "Debug (Attach) - Remote";
      hostName = "127.0.0.1";
      port = 5005;
    },
  }

```

Trying to run ` :lua require'dap'.continue()` gives the following error.

E5108: Error executing lua /home/matsu/.vim/bundle/nvim-dap/lua/dap/session.lua:644: bad argument #3 to 'getaddrinfo' (Invalid protocol hint)

### Steps to Reproduce

Copy the above configurations, try to run dap

### Expected Result

Dap connects and runs successfully

### Actual Result

Error above

**Comment by mfussenegger** [comment] 2022-01-10 12:13
`jdtls.setup_dap({ hotcodereplace = 'auto' })` already creates the adapter definition, you should remove the following block from your dap configuration:

```
dap.adapters.java = function(callback)
    -- here a function needs to trigger the `vscode.java.startDebugSession` LSP command
    -- The response to the command must be the `port` used below
    callback({
      type = 'server';
      host = '127.0.0.1';
      port = 5005;
    })
  end
```

**Comment by Matsuuu** [comment] 2022-01-11 18:49
After I removed the adapter, I get the following error: 

`No LSP client found that supports vscode.java.startDebugSession`

**Comment by mfussenegger** [comment] 2022-01-11 21:56
You have to follow the installation steps: https://github.com/mfussenegger/nvim-jdtls#debugger-via-nvim-dap

**Comment by kirillsafin** [comment] 2022-01-11 22:26
I have similar problem but with remote python. I get ` bad argument #3 to 'getaddrinfo' (Invalid protocol hint)` on trying to execute attach to remote python.
Here is my nvim-dap configuration
```
dap.adapters.python = {
  type = 'executable',
  command = python_exec,
  args = { '-m', 'debugpy.adapter' }
}

-- dap.adapters.remote_python = {
--   type = 'server',
--   host = '127.0.0.1',
--   port = 5678
-- }

dap.adapters.remote_python = function (callback)
  callback({
    type = 'server',
    host = '127.0.0.1',
    port = 5678
  })
end

dap.configurations.python = {
  {
    type = 'python',
    name = 'Launch File',
    request = 'launch',
    program = '${file}',
    pythonPath = python_exec
  },
  {
    type = 'remote_python' ,
    name = "Attach",
    request = "attach",
    mode = "remote",
    connect = {
      port = 5678,
      host = '127.0.0.1',
    },
    cwd = vim.fn.getcwd(),
    pathMappings = {
      {
        localRoot = vim.fn.getcwd(),
        remoteRoot = "/app",
      },
    },
  }
}
```
*Launch File* works fine. But the *Attach* fails.

**Comment by mfussenegger** [comment] 2022-01-12 08:42
Which neovim version are you using?

**Comment by Matsuuu** [comment] 2022-01-12 08:53
```
NVIM v0.6.0-dev+46-g682247b52
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

```

**Comment by mfussenegger** [comment] 2022-01-12 08:57
Could you also post the output of `:lua print(vim.loop.version_string())` ?

**Comment by Matsuuu** [comment] 2022-01-12 08:57
1.34.2

**Comment by Matsuuu** [comment] 2022-01-12 09:32
I updated to the nvim appimage since the latest master borks a lot of plugins.

Current setup:

```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

```

```
1.42.0
```

**Comment by kirillsafin** [comment] 2022-01-12 12:32
I have *debian testing* and have Neovim 0.6.1 installed via debian *apt* package manager. (I will add later the output of `:lua print(vim.loop.version_string())`)

**Comment by mfussenegger** [comment] 2022-01-12 17:41
@kirillsafin can you try with https://github.com/mfussenegger/nvim-dap/pull/407 ? (and please still post the output of `:lua print(vim.loop.version_string()))`

**Comment by Matsuuu** [comment] 2022-01-12 19:19
Tried dumping the commands @ https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls/util.lua#L9

```
Commands  { [1] = java.edit.organizeImports,[2] = java.project.refreshDiagnostics,[3] = java.project.import,[4] = java.navigate.openTypeHierarchy,[5]
= java.project.removeFromSourcePath,[6] = java.project.listSourcePaths,[7] = java.project.resolveStackTraceLocation,[8] = java.project.getAll,[9] = ja
va.project.isTestFile,[10] = java.project.getClasspaths,[11] = java.navigate.resolveTypeHierarchy,[12] = java.edit.stringFormatting,[13] = java.projec
t.getSettings,[14] = java.project.updateSourceAttachment,[15] = java.project.resolveSourceAttachment,[16] = java.project.addToSourcePath,}

```

Seems like for some reason the ` vscode.java.startDebugSession` command is missing from the LSP setup. Wonder why, and how to fix it?

**Comment by Matsuuu** [comment] 2022-01-12 20:57
Allright I got it solved at my end. Turns out I had missed the part where you had to install the `java-debug` library.

After installing it and adding 

```
init_options = {
  bundles = {
    "/path/to/java-debug/foo.version.jar"
  }
}
```

I got it working.

**Comment by kirillsafin** [comment] 2022-01-12 21:01
I have also 1.42.0 version and #407 haven't solved my issue.

**Comment by mfussenegger** [comment] 2022-01-13 09:46
@kirillsafin 

Do you also get the error if you run the following?

```
:lua vim.loop.getaddrinfo('localhost', nil, { protocol = 'tcp' }, function(err, addresses) print(vim.inspect(err)); print(vim.inspect(addresses)) end)
```

I'm not able to reproduce the issue with 1.42.0 and according to some comments in the luv repository it should have been fixed with 1.41

**Comment by kirillsafin** [comment] 2022-01-13 20:13
@mfussenegger yes I get the same error.
```
E5108: Error executing lua [string ":lua"]:1: bad argument #3 to 'getaddrinfo' (Invalid protocol hint)                                                         
stack traceback:
        [C]: in function 'getaddrinfo'
        [string ":lua"]:1: in main chunk
```
It seems like it is a problem on my side. 
Can you share the link to this luv repository to me. Maybe I can also read some comments and figure out what is going wrong on my device.

**Comment by q12321q** [comment] 2022-01-14 14:37
@kirillsafin I have the same error on my side after upgrading to the latest version of nvim-dap. Did you find a solution? The only thing that works for me is to rollback the upgrade.

**Comment by mfussenegger** [comment] 2022-01-14 16:09
Could you try with https://github.com/mfussenegger/nvim-dap/pull/411 ?

**Comment by q12321q** [comment] 2022-01-14 18:02
@mfussenegger Works for me!
Thanks

**Comment by kirillsafin** [comment] 2022-01-14 18:10
I get also no error and the debugger connects. I guess I have now some mapping issue.
Thank you @mfussenegger.

**Closed** 2022-01-14 21:23 UTC
