### ISSUE TITLE
error when entering a function in multithread program

### ISSUE THREAD

**Issue by kdamaski** [mfussenegger/nvim-dap#764] opened 2022-11-25 12:49 UTC
### Debug adapter definition and debug configuration

<pre>
local M = {}

M.config = function()
	local dap = require "dap"
	dap.adapters.lldb = {
		type = 'executable',
		command = '/usr/bin/lldb-vscode', -- adjust as needed, must be absolute path
		name = 'lldb'
	}

	dap.configurations.cpp = {
		{
			-- If you get an "Operation not permitted" error using this, try disabling YAMA:
			--  echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
			name = "Attach to process",
			type = 'cpp', -- Adjust this to match your adapter name (`dap.adapters.<name>`)
			request = 'attach',
			pid = require('dap.utils').pick_process,
			args = {},
		},
		{
			env = function()
				local variables = {}
				for k, v in pairs(vim.fn.environ()) do
					table.insert(variables, string.format("%s=%s", k, v))
				end
				return variables
			end,
			name = 'Launch',
			type = 'lldb',
			request = 'launch',
			program = function()
				return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
			end,
			cwd = '${workspaceFolder}',
			stopOnEntry = false,
			args = {},

			-- 💀
			-- if you change `runInTerminal` to true, you might need to change the yama/ptrace_scope setting:
			--
			--    echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
			--
			-- Otherwise you might get the following error:
			--
			--    Error on launch: Failed to attach to the target process
			--
			-- But you should be aware of the implications:
			-- https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html
			-- runInTerminal = false,
		},
	}
	dap.configurations.c = dap.configurations.cpp
	dap.configurations.rust = dap.configurations.cpp

	lvim.builtin.dap = {
		active = false,
		on_config_done = nil,
		breakpoint = {
			text = "",
			texthl = "LspDiagnosticsSignError",
			linehl = "",
			numhl = "",
		},
		breakpoint_rejected = {
			text = "",
			texthl = "LspDiagnosticsSignHint",
			linehl = "",
			numhl = "",
		},
		stopped = {
			text = "",
			texthl = "LspDiagnosticsSignInformation",
			linehl = "DiagnosticUnderlineInfo",
			numhl = "LspDiagnosticsSignInformation",
		},
	}
end

M.setup = function()
	local dap = require "dap"

	if lvim.use_icons then
		vim.fn.sign_define("DapBreakpoint", lvim.builtin.dap.breakpoint)
		vim.fn.sign_define("DapBreakpointRejected", lvim.builtin.dap.breakpoint_rejected)
		vim.fn.sign_define("DapStopped", lvim.builtin.dap.stopped)
	end

	dap.defaults.fallback.terminal_win_cmd = "50vsplit new"

	lvim.builtin.which_key.mappings["d"] = {
		name = "Debug",
		t = { "<cmd>lua require'dap'.toggle_breakpoint()<cr>", "Toggle Breakpoint" },
		b = { "<cmd>lua require'dap'.step_back()<cr>", "Step Back" },
		c = { "<cmd>lua require'dap'.continue()<cr>", "Continue" },
		C = { "<cmd>lua require'dap'.run_to_cursor()<cr>", "Run To Cursor" },
		d = { "<cmd>lua require'dap'.disconnect()<cr>", "Disconnect" },
		g = { "<cmd>lua require'dap'.session()<cr>", "Get Session" },
		i = { "<cmd>lua require'dap'.step_into()<cr>", "Step Into" },
		o = { "<cmd>lua require'dap'.step_over()<cr>", "Step Over" },
		u = { "<cmd>lua require'dap'.step_out()<cr>", "Step Out" },
		p = { "<cmd>lua require'dap'.pause()<cr>", "Pause" },
		r = { "<cmd>lua require'dap'.repl.toggle()<cr>", "Toggle Repl" },
		s = { "<cmd>lua require'dap'.continue()<cr>", "Start" },
		q = { "<cmd>lua require'dap'.close()<cr>", "Quit" },
	}

	if lvim.builtin.dap.on_config_done then
		lvim.builtin.dap.on_config_done(dap)
	end
end

-- TODO put this up there ^^^ call in ftplugin

-- M.dap = function()
--   if lvim.plugin.dap.active then
--     local dap_install = require "dap-install"
--     dap_install.config("python_dbg", {})
--   end
-- end
--
-- M.dap = function()
--   -- gem install readapt ruby-debug-ide
--   if lvim.plugin.dap.active then
--     local dap_install = require "dap-install"
--     dap_install.config("ruby_vsc_dbg", {})
--   end
-- end

return M

</pre>

### Debug adapter version

latest probably i installed a couple days ago

### Steps to Reproduce

I ran this project :  https://gitlab.com/kostasfeed/hy486.git
which is 3 files and less than 200 lines total. I put breakpoint in delete function of the list. But i think the most useful thing to watch is the log report below

### Expected Result

enter the function

### Actual Result

Error executing vim.schedule lua callback: ...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1216: attempt to concatenate field 'message' (a nil value)                       
stack traceback:
        ...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1216: in function 'callback'
        ...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:846: in function <...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:841>

<p style="{color:green;}">All of this likely is a programmatic fault of mine. What i would really like to know though is how to use local configs per projext . The config file contents above are my global settings in lunarvim and i would prefer to move that in my config.lua . When i tried to do so my config was crushing so i let it like that. I think i could put a json file locally so the adapter can take all the info require to run my program e.g. args. Thanks in advance and sorry if i wasted the bug report for a question. I didn't find a question form when i clicked on issues.</p>

**Comment by mfussenegger** [comment] 2022-11-25 15:48
>  I didn't find a question form when i clicked on issues.

Because questions should go to the discussions:

![image](https://user-images.githubusercontent.com/38700/204019071-053bd823-db53-4ddc-abdf-16a9d633defe.png)

> All of this likely is a programmatic fault of mine.

That error shouldn't happen. Can you share the logs from a debug session up until the error happens? See `dap.set_log_level()` and `:DapShowLog`

> What i would really like to know though is how to use local configs per projext .

See `:help dap-launch.json`

**Comment by kdamaski** [comment] 2022-11-25 19:06
Hello and thanks for reply. The dap.log file is 5k lines long. Is that from a single session?? I think i had set the log level to debug when running. Anyway an interesting warn that repeats in log is this : 
[ WARN ] 2022-11-25T14:59:32Z+0200 ] ...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:827 ]	"No callback for "	{
  body = {
    allThreadsContinued = true
  },
  command = "continue",
  request_seq = 76,
  seq = 0,
  success = true,
  type = "response"
}

There is no [ERROR] clause. Also i would like to mention that the bug in my program was because i had forgotten to unlock a couple of mutexes and the program was being locked in a normal execution (threads were spinning on the mutex lock). Maybe it is relevant maybe not. So In order to reproduce i would have to fallback the code which is ok if that's necessary for the debugging of the error. So please specify if i should send you this file of 5k lines or empty dap.log and try reproduce the error with another log level set by func dap.set_log_level.

**Comment by mfussenegger** [comment] 2023-01-05 11:20
This warning would point to an issue with the debug adapter - maybe it sent multiple responses for the same request.

Closing this for now as I can't reproduce this. If you've a minimal reproduction that works reliably please add the information

**Closed by mfussenegger** 2023-01-05 11:20 UTC
