### ISSUE TITLE
[Debug Config] Allow the debugger to read environment variables from "envFile" in launch.json

### ISSUE THREAD

**Issue by thanhdatvo** [mfussenegger/nvim-dap#1128] opened 2024-01-04 18:56 UTC
### Problem Statement

Currently the debugger is unable to read environment variables from "envFile" in launch.json

### Possible Solutions

Please help to get environment variables from "envFile" in launch.json at set it before debugger runs, or show me where can I start to make change and create a pr.

**Comment by mfussenegger** [comment] 2024-01-04 19:13
Duplicate of https://github.com/mfussenegger/nvim-dap/issues/543

**Closed by mfussenegger** 2024-01-04 19:13 UTC
