### ISSUE TITLE
codelldb Issue with command output visibility in debug DAP UI

### ISSUE THREAD

**Issue by Mike-18awq** [mfussenegger/nvim-dap#1260] opened 2024-06-09 18:03 UTC
### Debug adapter definition and debug configuration

I'm having trouble seeing command output while debugging in Neovim DAP UI. I've checked my config and tried a few things from the archives, but no luck.

Can anyone help troubleshoot this or suggest a fix?

### Debug adapter version

latest

### Steps to Reproduce

My config:
 local dap = require('dap')
    dap.adapters.codelldb = {
      type = 'server',
      port = "${port}",
      executable = {
        command = vim.fn.stdpath("data") .. '/mason/bin/codelldb',
        args = { "--port", "${port}" },
      },
    }
    dap.configurations.cpp = {
      {
        name = "Launch file",
        type = "codelldb",
        request = "launch",
        program = function()
          os.execute("clang++ -std=c++20 -glldb -fstandalone-debug " .. vim.fn.expand("%:p") .. " -o " .. vim.fn.expand("%:r"))
          return vim.fn.expand("%:r")
        end,
        cwd = '${workspaceFolder}',
        stopOnEntry = false,
      },
    }
https://github.com/Mike-18awq/dotfiles-Debian/blob/efdd45d29448ac0c2eabcb621de5ecf628546d05/config/nvim/lua/plugins/nvim-dap-ui.lua

### Expected Result

Command output as debugging progresses in the DAP UI terminal.

### Actual Result

https://github.com/mfussenegger/nvim-dap/assets/137745753/b886609e-771a-485d-a8a8-853139b86584

**Comment by igorlfs** [comment] 2024-07-06 16:20
Duplicate of #1061

**Closed** 2024-07-08 20:18 UTC
