### ISSUE TITLE
nvim-dap with Maven/Gradle projects

### ISSUE THREAD

**Issue by MrcJkb** [mfussenegger/nvim-dap#181] opened 2021-05-18 08:31 UTC
Hi,

first of all: Awesome tool-set! Your repos have played a major role in enabling my migration from IntelliJ IDEA to Neovim as my daily driver for Java development. Thanks for that!

I am facing one issue with nvim-dap: Everything is set up, and I can toggle breakpoints, etc.
If I understood correctly, the jdt.ls language server should auto-detect debug configurations for main files, and I should be able to launch them with: `lua require'dap'.continue()` from within a class that has a `main` method.

However, this prints the message: `No configuration found for java`.
Am I still missing something?

Here's the relevant excerpt from my LSP configuration:
```
config.on_attach = on_jdtls_attach -- setup_dap() is called on attach
config.on_init = function(client, _)
  client.notify('workspace/didChangeConfiguration', { settings = config.settings })
end
local extendedClientCapabilities = require'jdtls'.extendedClientCapabilities
extendedClientCapabilities.resolveAdditionalTextEditsSupport = true
local bundles = {
  vim.fn.glob(home .. "/git/clones/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar")
}
vim.list_extend(bundles, vim.split(vim.fn.glob(home .. "/git/clones/vscode-java-test/server/*.jar"), "\n"))
config.init_options = {
  extendedClientCapabilities = extendedClientCapabilities;
  bundles = bundles;
}
jdtls.start_or_attach(config)
```

**Comment by MrcJkb** [comment] 2021-05-18 08:48
`:lua print(vim.inspect(require'dap'.adapters))` prints an empty `Table`, so it appears that `jdtls.setup_dap()` is either not called or fails before creating the configuration.
I have tried manually calling it, but so far to no avail.

**Comment by MrcJkb** [comment] 2021-05-18 09:15
It appears to be an LSP issue.
```
:lua require('jdtls.util').execute_command({command = 'vscode.java.resolveMainClass'}, function(err0, mainclasses) print(vim.inspect(mainclasses)) end)
```
prints an empty `Table`.

**Comment by theHamsta** [comment] 2021-05-18 09:20
Hi, I had this issue too. The language server takes a long time on my machine to load the gradle project so 'vscode.java.resolveMainClass' won't be successfull often on the first call and then the calls subsequent to this method won't be complete. I deleted these lines  https://github.com/mfussenegger/nvim-jdtls/blob/6fa8c5a9459504c2a090c0028b27da951e35a354/lua/jdtls/dap.lua#L373-L357 and call the setup_dap function a few times later. It can take 30s or so until the server finds all main classes. Also this doesn't work always on my machine but usually after some time passed it discovers all main methods.

**Comment by MrcJkb** [comment] 2021-05-18 10:28
> Hi, I had this issue too. The language server takes a long time on my machine to load the gradle project so 'vscode.java.resolveMainClass' won't be successfull often on the first call and then the calls subsequent to this method won't be complete. I deleted these lines https://github.com/mfussenegger/nvim-jdtls/blob/6fa8c5a9459504c2a090c0028b27da951e35a354/lua/jdtls/dap.lua#L373-L357 and call the setup_dap function a few times later. It can take 30s or so until the server finds all main classes. Also this doesn't work always on my machine but usually after some time passed it discovers all main methods.

Thanks!
That got it to work in one of my gradle projects.
It's still not working in a maven subproject, but I can live with that. I guess a workaround would be to configure the LSP to look for the subproject root, rather than the project root.

**Comment by MrcJkb** [comment] 2021-05-18 11:17
I have added a PR to nvim-jdtls, which solves this issue for me.

**Comment by mfussenegger** [comment] 2021-05-19 17:31
Closing this here since it is nivm-jdtls / eclipse jdt related.

If you could create a small reproduction repo for the maven subproject issue I could look into that. Might be some classpath setup hiccups or something like that.

**Closed by mfussenegger** 2021-05-19 17:31 UTC
