### ISSUE TITLE
stopOnEntry not working for c and cpp

### ISSUE THREAD

**Issue by Martinits** [mfussenegger/nvim-dap#829] opened 2023-01-17 01:33 UTC
### Debug adapter definition and debug configuration

```lua
dap.adapters.lldb = {
    type = 'executable',
    command = '/usr/bin/lldb-vscode',
}

-- configurations
local executable_prompt = function()
    return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
end

dap.configurations.c = {
  {
    name = 'lldb-c',
    type = 'lldb',
    request = 'launch',
    program = executable_prompt,
    cwd = '${workspaceFolder}',
    stopOnEntry = true,
    args = {},
  },
}
```

### Debug adapter version

master

### Steps to Reproduce

1. any simple c or cpp file
2. compile with `-g`
3. launch dap
4. not jumping into source code and get notification: `Dap: Source not available, cannot jump to frame`

If unset stopOnEntry, and set any breakpoint, all things are good. I guess stopOnEntry makes dap break at the very beginning of the executable, probably inside c and cpp libraries before entering `main`, so dap cannot find sources.

### Expected Result

as above

### Actual Result

as above

**Comment by mfussenegger** [comment] 2023-01-17 18:11
Sounds like an issue with the debug adapter. You could post the logs to be sure?

**Comment by Martinits** [comment] 2023-01-18 01:54
here: https://pastebin.pl/view/8ebf89bc

**Comment by Martinits** [comment] 2023-01-18 03:28
And same issue on rust (also using lldb-vscode), as tested.

**Comment by mfussenegger** [comment] 2023-01-18 06:55
Thanks for the logs. Turns out this was a regression that should be fixed with https://github.com/mfussenegger/nvim-dap/pull/831

**Closed** 2023-01-18 06:54 UTC
