### ISSUE TITLE
Error pops up on Neovim 0.10 in WINDOWS 11

### ISSUE THREAD

**Issue by jacknicklenson** [mfussenegger/nvim-dap#1280] opened 2024-07-17 14:12 UTC
### Debug adapter definition and debug configuration

![Ekran görüntüsü 2024-07-17 165952](https://github.com/user-attachments/assets/be9f22ac-ce28-4165-afca-e35ce598d7e8)

installed adapter via `winget install LLVM.LLVM` which is lldb-dap.
No issue on Linux. Only on Windows. Debugging session continue without issue though. However, every time a I step-over / step-into, this error pops up annoyingly but debugging continues without termination.
minimal configuaration:
```
require "paq" {
  "mfussenegger/nvim-dap",
}

local dap = require("dap")
dap.adapters.lldb = {
  type = 'executable',
  command = 'C:/Program Files/LLVM/bin/lldb-dap.exe',
  name = 'lldb'
}

dap.configurations.c = {
  {
    name = 'Launch Manually',
    type = 'lldb',
    request = 'launch',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = function()
      local args = vim.fn.input('Args: ', '', 'file')
      local words = {}
      for v in args:gmatch('%S+') do
        table.insert(words, v)
      end
      if #words == 0 then
        return {}
      end
      return words
    end,
  },
}
```

### Debug adapter version

18.1.8 (LLVM version which comes with lldb-dap.exe)

### Steps to Reproduce

Screenshot above from neovim official source code. (In my config I don't use `.vscode/launch.json`. It prompts for executable location and space-separated arguments)
1. Open `src/nvim/main.c`.
2. `:DapToggleBreakpoint`.
3. `:DapContinue`
4. Then this error pops up.

### Expected Result

Shouldn't pop up a error.

### Actual Result

Error pops up like in screenshot.

**Comment by mfussenegger** [comment] 2024-07-17 14:29
Sounds like a duplicate of https://github.com/mfussenegger/nvim-dap/issues/1196

**Closed by mfussenegger** 2024-07-17 14:29 UTC
